using System;

namespace Model.Entity
{


    public class Eventos
    {
        public int Id_Evento { get; set; }
        public Nullable<int> Id_Loja { get; set; }
        public Nullable<System.DateTime> Dt_Inicio { get; set; }
        public Nullable<System.DateTime> Dt_Fim { get; set; }
        public string Tipo_Evento { get; set; }
        public string Titulo { get; set; }
        public string Tipo_Exibicao { get; set; }
        public int Estados { get; set; }

        //------------------------------------------------------------------------------
        // <auto-generated>
        //     This code was generated from a template.
        //
        //     Manual changes to this file may cause unexpected behavior in your application.
        //     Manual changes to this file will be overwritten if the code is regenerated.
        // </auto-generated>
        //------------------------------------------------------------------------------
            public string Subject { get; set; }
            public string Description { get; set; }
            public DateTime Start { get; set; }
            public DateTime Fim { get; set; }
            public string ThemeColor { get; set; }
            public bool IsFullDay { get; set; }
        }
    }