//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatinDashboard.Presentation.MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaconXXXXX
    {
        public Nullable<int> Cim { get; set; }
        public Nullable<int> Id_Loja { get; set; }
        public Nullable<int> Id_Graduacao { get; set; }
        public Nullable<int> Id_Cargo { get; set; }
        public Nullable<int> Id_Condecoracao { get; set; }
        public string Nome { get; set; }
        public string Nome_Tratamento { get; set; }
        public string Grau { get; set; }
        public string Senha { get; set; }
        public string Situacao { get; set; }
        public string CPF { get; set; }
        public string Login { get; set; }
        public string Email { get; set; }
        public string Email_Outros { get; set; }
        public string Dt_Nascimento { get; set; }
        public string Naturalidade { get; set; }
        public string Uf { get; set; }
        public string Nacionalidade { get; set; }
        public string Religiao { get; set; }
        public string Escolaridade { get; set; }
        public string Sexo { get; set; }
        public string Tipo_Sanguíneo { get; set; }
        public string Estado_Civil { get; set; }
        public Nullable<System.DateTime> Data_Casamento { get; set; }
        public string Tipo_Di { get; set; }
        public string Num_Di { get; set; }
        public string Emissor_Di { get; set; }
        public string Dt_Emissao_Di { get; set; }
        public string Uf_Di { get; set; }
        public string Tit_Eleitor { get; set; }
        public string Zona_Eleitoral { get; set; }
        public string Secao_Eleitoral { get; set; }
        public string Nome_Pai { get; set; }
        public string Nome_Mae { get; set; }
        public string End_Res { get; set; }
        public string Bairro_Res { get; set; }
        public string Cidade_Res { get; set; }
        public string Uf_Res { get; set; }
        public string Cep_Res { get; set; }
        public string cx_postal { get; set; }
        public string celular { get; set; }
        public string tel_res { get; set; }
        public string fax { get; set; }
        public string obs { get; set; }
        public string correspondencia_end { get; set; }
        public byte[] foto { get; set; }
        public int Id_Macon { get; set; }
        public Nullable<System.DateTime> Dt_Iniciado { get; set; }
        public string Guide { get; set; }
    }
}
