//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatinDashboard.Presentation.MVC
{
    using System;
    using System.Collections.Generic;
    
    public partial class Repasses
    {
        public int indice { get; set; }
        public string Matricula { get; set; }
        public string Nome { get; set; }
        public string Categoria { get; set; }
        public string Vencimento { get; set; }
        public string Valor { get; set; }
        public string LCM { get; set; }
        public string Codigo { get; set; }
        public string sequencia { get; set; }
        public string Documento { get; set; }
        public string ValorRepasse { get; set; }
        public Nullable<bool> Pago { get; set; }
        public string CodRegional { get; set; }
        public string NomeRegional { get; set; }
        public string PN { get; set; }
        public string MesAno { get; set; }
        public string Ativo { get; set; }
        public string Conta { get; set; }
        public string Empresa { get; set; }
        public string DataPagto { get; set; }
    }
}
